// <auto-generated />
// Generated by scripts/sync-manifest-trust.mjs  -  do not edit by hand.
// Source: scripts/.env.release signing key @ 2026-07-18T13:26:47Z

namespace StacksAtlas.Core.Services.Updates;

public static partial class ReleaseManifestTrust
{
    /// <summary>Ed25519 SPKI (DER, base64) trusted to verify release manifests.</summary>
    public const string EmbeddedPublicKeySpkiBase64 = "MCowBQYDK2VwAyEApVkNXOt+Gr/tjK8aQCWXkPCwGeVJVElWUeevsmXqV78=";
}
