<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);SYSLIB0057;SYSLB0060;CS0618;CA1416;CS0219</NoWarn>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <None Remove="Resources\oui.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\oui.json" />
    <EmbeddedResource Include="Resources\Recog\http_servers.xml" />
    <EmbeddedResource Include="Resources\Recog\snmp_sysDescr.xml" />
    <EmbeddedResource Include="Resources\FingerprintLibrary.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Chaos.NaCl.Standard" Version="1.0.0" />
    <PackageReference Include="ArpLookup" Version="2.0.3" />
    <PackageReference Include="Lextm.SharpSnmpLib" Version="12.5.2" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.9" />
    <PackageReference Include="QuestPDF" Version="2025.12.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="3.119.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    <PackageReference Include="System.DirectoryServices.Protocols" Version="10.0.9" />
    <PackageReference Include="System.Management" Version="10.0.9" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageReference Include="SourceGear.sqlite3" Version="3.50.4.5" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageReference Include="Zeroconf" Version="3.7.16" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Network\" />
  </ItemGroup>

</Project>
