// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using StacksAtlas.Core.Data.Hub;

#nullable disable

namespace StacksAtlas.Core.Data.Hub.Migrations
{
    [DbContext(typeof(HubDbContext))]
    [Migration("20260624120000_AddDeviceTypeManualFlag")]
    partial class AddDeviceTypeManualFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model is defined in HubDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
