// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StacksAtlas.Core.Data.Hub;

#nullable disable

namespace StacksAtlas.Core.Data.Hub.Migrations
{
    [DbContext(typeof(HubDbContext))]
    [Migration("20260524134338_AddDiscoveryProvenance")]
    partial class AddDiscoveryProvenance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("StacksAtlas.Core.Models.AlertEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AlertType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Building")
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Room")
                        .HasColumnType("TEXT");

                    b.Property<string>("SentToEmails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SentToWebhooks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NodeId", "TriggeredAt");

                    b.ToTable("AlertEvents");
                });

            modelBuilder.Entity("StacksAtlas.Core.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AlertsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AverageLatencyMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Building")
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStrikes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeepScanIssues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscoveryInterfaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscoveryInterfaceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscoveryScopeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstDiscoveredUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlapCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpTitle")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdentitySource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IgnoredSecurityIssues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDiscoveryProvenanceManuallySet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsModelManuallySet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVendorManuallySet")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastDbWriteUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastLatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastStateChangeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSweepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatencyHistory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ManagedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagedByUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenPorts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Room")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecurityGrade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityIssues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SnmpLastCheck")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnmpSysDescr")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnmpSysName")
                        .HasColumnType("TEXT");

                    b.Property<int>("StabilityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSweepsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSweepsSeen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<double>("UptimePercent")
                        .HasColumnType("REAL");

                    b.Property<string>("Vendor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NodeId", "MacAddress", "DiscoveryScopeId")
                        .IsUnique()
                        .HasFilter("MacAddress IS NOT NULL");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("StacksAtlas.Core.Models.FederatedLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NodeId", "Timestamp");

                    b.ToTable("FederatedLogs");
                });

            modelBuilder.Entity("StacksAtlas.Core.Models.FederatedNode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Building")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateSerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DatabaseSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DelegateAlertDispatch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HardwareId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HttpPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HttpsPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIdentityImported")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseTier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OS")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OverrideAlertSettings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OverrideSiemSettings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Room")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanSettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SyncAlertSettings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncSiemSettings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncSsoSettings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncUserRegistry")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncUsers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("StacksAtlas.Core.Models.SystemEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Building")
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Room")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subnet")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NodeId", "Timestamp");

                    b.ToTable("SystemEvents");
                });

            modelBuilder.Entity("StacksAtlas.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlertEmail")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AlertOnDeviceDown")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlertOnDeviceUp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlertOnNewDevice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlertSeverity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AlertsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginNodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreferredWebhookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredWebhookIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WebhookEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StacksAtlas.Core.Models.WebhookConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlertSeverity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CircuitResetAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SigningSecret")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerEvents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Webhooks");
                });
#pragma warning restore 612, 618
        }
    }
}
